//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballAppListView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goals
    {
        public int id_player { get; set; }
        public int id_match { get; set; }
        public int Score { get; set; }
        public int id_club { get; set; }
    
        public virtual Date_Location Date_Location { get; set; }
        public virtual Players Players { get; set; }
    }
}
